AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetID:
    Type: AWS::EC2::Subnet::Id
    Default: "<update-your-subnet-id>"
    Description: Subnet to deploy EC2 instance into
  SecurityGroupIDs:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: "<update-your-security-group-id>"
    Description: List of Security Groups to add to EC2 instance
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: "ec2test"
    Description: >-
      Name of an existing EC2 KeyPair to enable SSH access to the instance
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.micro
  ImageId:
    Description: EC2 instance ImageId
    Type: String
    Default: ami-08e4e35cccc6189f4

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
#    Mappings:
#      AWSRegionToAMI:
#        us-east-1:
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds: !Ref SecurityGroupIDs
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetID
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}
